[workspace]

resolver = "2"

members = [
  "demo/protocol-demo",
  "mithril-aggregator",
  "mithril-client",
  "mithril-common",
  "mithril-relay",
  "mithril-signer",
  "mithril-stm",
  "mithril-test-lab/mithril-end-to-end",
]

[workspace.package]
authors = ["dev@iohk.io"]
documentation = "https://mithril.network/doc"
edition = "2021"
homepage = "https://mithril.network"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/mithril/"
