[package]
name = "mithril-common"
version = "0.2.129"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[[bench]]
name = "digester"
harness = false

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
bech32 = "0.9.1"
blake2 = "0.10.6"
chrono = { version = "0.4.31", features = ["serde"] }
digest = "0.10.7"
ed25519-dalek = { version = "2.0.0", features = ["rand_core", "serde"] }
fixed = "1.24.0"
glob = "0.3.1"
hex = "0.4.3"
http = "0.2.9"
jsonschema = "0.17.1"
kes-summed-ed25519 = { version = "0.2.1", features = [
    "serde_enabled",
    "sk_clone_enabled",
] }
mockall = "0.11.4"
nom = "7.1.3"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
rayon = "1.8.0"
semver = "1.0.19"
serde = { version = "1.0.188", features = ["derive"] }
serde_bytes = "0.11.12"
serde_cbor = "0.11.2"
serde_json = "1.0.107"
serde_with = "3.3.0"
serde_yaml = "0.9.25"
sha2 = "0.10.8"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-scope = "4.4.0"
sqlite = { version = "0.31.1", features = ["bundled"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
typetag = "0.2.13"
walkdir = "2.4.0"
warp = "0.3.6"

[target.'cfg(not(windows))'.dependencies]
# non-windows: use default rug backend
mithril-stm = { path = "../mithril-stm" }

[target.'cfg(windows)'.dependencies]
# Windows doesn't support rug backend, fallback to num-integer
mithril-stm = { path = "../mithril-stm", default-features = false }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
reqwest = { version = "0.11.22", features = ["json"] }
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"

[build-dependencies]
glob = "0.3.1"
semver = "1.0.19"
serde_json = "1.0.107"
serde_yaml = "0.9.25"

[features]
default = []
portable = [
    "mithril-stm/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
allow_skip_signer_certification = []
