[package]
name = "mithrildemo"
version = "0.1.22"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
base64 = "0.21.4"
blake2 = "0.10.6"
clap = { version = "4.4.6", features = ["derive"] }
hex = "0.4.3"
log = "0.4.20"
mithril-common = { path = "../../mithril-common" }
rand_chacha = "0.3.1"
rand_core = "0.6.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

[target.'cfg(not(windows))'.dependencies]
# non-windows: use default rug backend
mithril-stm = { path = "../../mithril-stm" }

[target.'cfg(windows)'.dependencies]
# Windows doesn't support rug backend, fallback to num-integer
mithril-stm = { path = "../../mithril-stm", default-features = false }

[features]
portable = ["mithril-common/portable", "mithril-stm/portable"]
